language: go
go:
  - 1.7
  - 1.8
  - 1.9
  - '1.10'
  - '1.11'
  - master

sudo: false

before_install:
  - go get -t -v ./...

install:
  - go get
  - go build

script:
  - make test
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - go: master
