language: go
go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - '1.10'
  - master

sudo: false

before_install:
  - go get github.com/mattn/goveralls

install:
  - go get
  - go build

script:
  - make test
  - go test -coverprofile=cover.out github.com/mozillazg/go-cos
  - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=cover.out
  - |
    if [[ $TRAVIS_GO_VERSION == 1.10* ]]; then
      make example
    fi

matrix:
  allow_failures:
    - go: 1.6
    - go: 1.7
    - go: master
